spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: testtest
  jpa:
    hibernate:
      ddl-auto: create-drop

config:
  site:
    - url: https://www.svetlovka.ru
      name: Библиотека Светловка

    - url: https://dombulgakova.ru
      name: Дом Булгакова

    - url: https://www.playback.ru
      name: Телефоны